package com.edgeppg.app.integrity

/**
 * Stage 13 Task 6 — Transcript builder.
 *
 * Bridges the session-level data (challenge id, expected sequence,
 * final decision, quality metrics) to the [IntegrityManager.Telemetry]
 * shape, then signs it via [IntegrityManager.sign] to produce a
 * [IntegrityManager.Envelope] for transport.
 *
 * We do NOT duplicate the [IntegrityManager.Telemetry] structure or
 * the [IntegrityManager.canonicalJson] byte format here. The
 * canonical byte layout and the field set are owned by
 * [IntegrityManager]; we just construct a [Telemetry] value and
 * delegate signing to it. Any future change to the canonical
 * payload (Requirements FR-CRY-3) is therefore a one-file change
 * to [IntegrityManager].
 *
 * Default values for [IntegrityManager.Telemetry] are designed to
 * match the verifier's expectations when a metric is unavailable —
 * `0f` for floating-point metrics means "not measured", and the
 * timestamp defaults to `System.currentTimeMillis()`. We do NOT
 * silently zero-fill canonical schema fields (Architecture §11);
 * the verifier side distinguishes "0" from "missing" via NaN at
 * higher layers, but for rPPG-class float metrics a `0f` default
 * is the documented convention used by the Stage 4 rPPG DSP.
 */
object TranscriptBuilder {

    /**
     * Build a [IntegrityManager.Telemetry] from the per-session data
     * the rest of the pipeline produces. The caller may override any
     * field via [extra] — useful when an upstream module has a more
     * specific value than the default.
     */
    fun telemetry(
        challengeId: String,
        expectedSeq: String,
        decision: IntegrityManager.Decision,
        confidence: Float,
        signalQuality: Float,
        hrBpm: Float = 0f,
        snr: Float = 0f,
        roiCorr: Float = 0f,
        timestampMs: Long = System.currentTimeMillis(),
    ): IntegrityManager.Telemetry = IntegrityManager.Telemetry(
        challengeId = challengeId,
        expectedSeq = expectedSeq,
        decision = decision,
        confidence = confidence,
        signalQuality = signalQuality,
        hrBpm = hrBpm,
        snr = snr,
        roiCorr = roiCorr,
        timestampMs = timestampMs,
        // Nonce is auto-generated by IntegrityManager.Telemetry's
        // default — we deliberately do not expose it here so the
        // nonce policy stays in one place.
    )

    /**
     * Build + sign. Returns null iff [IntegrityManager.sign] returns
     * null (no hardware key or signing failure). The result is the
     * exact wire shape consumed by [com.edgeppg.app.transport.Transport].
     */
    fun sign(
        challengeId: String,
        expectedSeq: String,
        decision: IntegrityManager.Decision,
        confidence: Float,
        signalQuality: Float,
        hrBpm: Float = 0f,
        snr: Float = 0f,
        roiCorr: Float = 0f,
        timestampMs: Long = System.currentTimeMillis(),
    ): IntegrityManager.Envelope? = IntegrityManager.sign(
        telemetry(
            challengeId = challengeId,
            expectedSeq = expectedSeq,
            decision = decision,
            confidence = confidence,
            signalQuality = signalQuality,
            hrBpm = hrBpm,
            snr = snr,
            roiCorr = roiCorr,
            timestampMs = timestampMs,
        )
    )
}
